/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-09-25 09:51:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP.IpetB;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.PetSpecies.model.*;
import com.petInformation.model.*;
import com.PetImage.model.*;
import com.PetView.model.*;
import com.PetBreed.model.*;

public final class adoption_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	PetSpeciesService speciesSvc = new PetSpeciesService();
	pageContext.setAttribute("speciesSvc", speciesSvc);
	List<PetSpeciesVO> species = speciesSvc.getAll();
	pageContext.setAttribute("species", species);

	// 	PetInformationService petInfoSvc = new PetInformationService();
	// 	List<PetInformationVO> list = petInfoSvc.getAll();
	// 	pageContext.setAttribute("list", list);

	PetBreedService breedsvc = new PetBreedService();
	pageContext.setAttribute("breedSvc", breedsvc);
	List<PetBreedVO> breedlist = breedsvc.getAll();
	pageContext.setAttribute("breedList", breedlist);

	PetImageService picSvc = new PetImageService();
	List<PetImageVO> imageList = picSvc.getAll();
	pageContext.setAttribute("PetImageVO", imageList);

	// 		PetViewService petviewSvc = new PetViewService();
	// 		List<PetViewVO> list2 = petviewSvc.getAll();
	// 	    pageContext.setAttribute("list2", list2);

	List<PetViewVO> list2 = (List<PetViewVO>) request.getAttribute("petViewList"); //使用者輸入查詢條件後來查到東西list2
	if (list2 == null) { // 一開始如果list2沒東西，就自動產生預先想呈現的內容
		PetViewService petviewSvc = new PetViewService(); //把view裡面的東西生出來
		list2 = petviewSvc.getAll();
	}
	pageContext.setAttribute("list2", list2); //把list2set到page給本頁用
	// 	System.out.println("AAAAAA"+list2.size());

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <script src=\"js/main.js\"></script> -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/css/nav.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/js/main.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCVTvj_0kUlIT4NDFTo4AV0ZJbliitGrPQ\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//定義經緯度位置: 以中央大學為中心\r\n");
      out.write("\t\tvar latlng = new google.maps.LatLng(24.9686, 121.1956658);\r\n");
      out.write("\r\n");
      out.write("\t\t//設定地圖參數\r\n");
      out.write("\t\tvar mapOptions = {\r\n");
      out.write("\t\t\tzoom : 13, //初始放大倍數\r\n");
      out.write("\t\t\tcenter : latlng, //中心點所在位置\r\n");
      out.write("\t\t// mapTypeId: google.maps.MapTypeId.ROADMAP //正常2D道路模式\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t//在指定DOM元素中嵌入地圖\r\n");
      out.write("\t\tvar map = new google.maps.Map(document.getElementById(\"map-canvas\"),\r\n");
      out.write("\t\t\t\tmapOptions);\r\n");
      out.write("\t\t//加入標示點(Marker)\r\n");
      out.write("\t\tvar marker = new google.maps.Marker({\r\n");
      out.write("\t\t\tposition : latlng, //經緯度\r\n");
      out.write("\t\t\ttitle : \"資策會\", //顯示文字\r\n");
      out.write("\t\t\tmap : map\r\n");
      out.write("\t\t//指定要放置的地圖對象\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\tgoogle.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write("</script>\r\n");
      out.write("<title>iPet愛動物</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--第一區：nav區-->\r\n");
      out.write("\t<div class=\"b_nav\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--左欄：logo區-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-2 col-sm-2\">\r\n");
      out.write("\t\t\t\t<a class=\"logo\" href=\"index.html\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/Ipet_Logo .png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--左欄：logo區 end-->\r\n");
      out.write("\t\t\t<!--手機版的漢堡選單開始-->\r\n");
      out.write("\t\t\t<div class=\"burger-menu\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--手機版的漢堡選單結束-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--右欄：購物車等icon＋選單區-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-10 col-sm-10 rightbar text-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--購物車、註冊、登入、會員專區（登入成功後，登入兩字變為會員專區）-->\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon shopping\">\r\n");
      out.write("\t\t\t\t\t\t\t<span> <a href=\"#\"> <i class=\"fa fa-cart-plus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> 購物車\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon member\">\r\n");
      out.write("\t\t\t\t\t\t\t<span> <a href=\"#\"> <i class=\"fa fa-user-o\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> 加入會員\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon login\">\r\n");
      out.write("\t\t\t\t\t\t\t<span> <a href=\"#\"> <i class=\"fa fa-user-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> 登入\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--購物車、註冊、登入、會員專區（登入成功後，登入兩字變為會員專區）end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--選單區-->\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"adopt.html\">我要認養</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">自我評估</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"adopt.html\">認養總覽</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"addadoption.html\">我要送養</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">送養須知</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"addadoption.html\">新增送養</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"shopping.html\">購物商城</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">討論區</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">寵物牆</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">活動專區</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">本版活動</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">領養分享</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--選單區 end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--右欄：購物車等icon＋選單區 end-->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--第一區：nav區 end-->\r\n");
      out.write("\r\n");
      out.write("\t<!--各頁主內容寫在這-->\r\n");
      out.write("\t<div class=\"adopt-search-content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"left-sidebar col-xs-12\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<!--搜尋條件區開始-->\r\n");
      out.write("\t\t\t\t\t<form class=\"col-xs-12 col-sm-12\" METHOD=\"post\"\r\n");
      out.write("\t\t\t\t\t\tACTION=\"");
      out.print(request.getContextPath());
      out.write("/PetViewServlet\"\r\n");
      out.write("\t\t\t\t\t\tname=\"search\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"conditions-area\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"aaa\"></label> <input type=\"text\" name=\"textSearch\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"請輸入搜尋關鍵字\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"speciesNo\">動物類型</label> <select name=\"speciesNo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"petPosition\">動物所在縣市</label> <select id=\"petPosition\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"petPosition\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"台北市\">台北市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"新北市\">新北市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"桃園市\">桃園市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"新竹市\">新竹市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"新竹縣\">新竹縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"宜蘭縣\">宜蘭縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"基隆市\">基隆市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"台中市\">台中市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"彰化縣\">彰化縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"雲林縣\">雲林縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"苗栗縣\">苗栗縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"南投縣\">南投縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"高雄市\">高雄市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"台南市\">台南市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"嘉義市\">嘉義市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"嘉義縣\">嘉義縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"屏東縣\">屏東縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"台東縣\">台東縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"花蓮縣\">花蓮縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"澎湖縣\">澎湖縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"金門縣\">金門縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"連江縣\">連江縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"petAge\">年齡</label> <select id=\"petAge\" name=\"petAge\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"幼年\">幼年</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"成年\">成年</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"petPosition\">動物性別</label> <select name=\"petSex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"公\">公</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"母\">母</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-12 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"petView\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" id=\"search-now\">馬上搜尋</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-info\" id=\"search-more\">更多條件</button> -->\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--搜尋條件區結束-->\r\n");
      out.write("\t\t\t\t\t<!--其他區廣告開始-->\r\n");
      out.write("\t\t\t\t\t<div class=\"ad-area \">\r\n");
      out.write("\t\t\t\t\t\t<p>廣告區：熱門貼文或是認養心得或是認養需知。</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--其他區廣告結束-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"search-result col-xs-12 col-sm-9 col-sm-push-3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"map\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!--地圖搜尋開始-->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"map-search\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"\" value=\"\" placeholder=\"輸入地址查詢位置！\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--地圖搜尋結束-->\r\n");
      out.write("\t\t\t\t\t\t\t<!--google map顯示開始-->\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"map-canvas\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--google map顯示結束-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title-area left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab tab-active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/adoption.jsp\">依時間排序</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab\">依推薦排序</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"posts\">\r\n");
      out.write("\t\t\t\t\t\t<!--第1則-->\r\n");
      out.write("\t\t\t\t\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f2_reused = false;
      try {
        _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f2.setParent(null);
        // /JSP/IpetB/adoption.jsp(312,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f2.setVar("pet");
        // /JSP/IpetB/adoption.jsp(312,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list2}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
          if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class=\"box\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<div class=\"post-img col-xs-12 col-sm-4\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<img\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
              out.print(request.getContextPath());
              out.write("/JSP/IpetB/PetImage.do?petNo=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("&index=1\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"img-responsive\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<div class=\"post-text  col-xs-12  col-sm-8\">\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<h3>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<span> ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.speciesName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write(" </span> \r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"");
              out.print(request.getContextPath());
              out.write("/PetViewDatailServlet?petNo=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write('"');
              out.write('>');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</a>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"infomation\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<span><span style=\"color: black\">動物名稱：</span>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<span><span style=\"color: black\">品種：</span>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.breedName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<span><span style=\"color: black\">年齡：</span>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petAge}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span><br>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<span><span style=\"color: black\">地點：</span>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petPosition}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<span><span style=\"color: black\">性別：</span>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petSex}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<span><span style=\"color: black\">晶片：</span>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petIc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"description\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t<span><span style=\"color: black\">動物介紹：</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.situation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f2.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
        _jspx_th_c_005fforEach_005f2_reused = true;
      } finally {
        if (!_jspx_th_c_005fforEach_005f2_reused) {
          _jspx_th_c_005fforEach_005f2.release();
          _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f2);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--地圖＋領養方塊區結束-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /JSP/IpetB/adoption.jsp(201,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("species");
      // /JSP/IpetB/adoption.jsp(201,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${species}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${species.speciesNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${species.speciesName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f0_reused) {
        _jspx_th_c_005fforEach_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /JSP/IpetB/adoption.jsp(301,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMsgs}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<ul>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t\t\t</font>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f0_reused) {
        _jspx_th_c_005fif_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /JSP/IpetB/adoption.jsp(303,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("message");
      // /JSP/IpetB/adoption.jsp(303,8) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<li style=font-size:24px;>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</li>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f1_reused) {
        _jspx_th_c_005fforEach_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f1);
      }
    }
    return false;
  }
}
