/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-09-30 06:04:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP.IpetB;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.PetBreed.model.*;
import com.PetSpecies.model.*;
import com.petInformation.model.*;
import com.PetImage.model.*;
import java.util.*;

public final class adoptionList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// 	PetInformationVO petInfoVO = (PetInformationVO) request.getAttribute("PetInformationVO"); //記憶動物table寫錯資料時，其他正確的內容
	// 	PetBreedVO breedVOe = (PetBreedVO) request.getAttribute("PetBreedVO"); //記憶使用者輸入品種的選項，
	// 	PetSpeciesVO speciesVO = (PetSpeciesVO) request.getAttribute("PetSpeciesVO"); //記憶使用者輸入種類的選項
	// 	PetImageVO imageVO = (PetImageVO) request.getAttribute("PetImageVO"); //記憶使用者輸入的照片和標題
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>會員頁用</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"js/main.js\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCVTvj_0kUlIT4NDFTo4AV0ZJbliitGrPQ\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/js/Address.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/css/adopt.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      com.petInformation.model.PetInformationService infoSvc = null;
      infoSvc = (com.petInformation.model.PetInformationService) _jspx_page_context.getAttribute("infoSvc", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (infoSvc == null){
        infoSvc = new com.petInformation.model.PetInformationService();
        _jspx_page_context.setAttribute("infoSvc", infoSvc, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>寵物編號</th>\r\n");
      out.write("\t\t\t\t<th>動物名稱</th>\r\n");
      out.write("\t\t\t\t<th>送養標題</th>\r\n");
      out.write("\t\t\t\t<th>送養日期</th>\r\n");
      out.write("\t\t\t\t<th>狀態</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /JSP/IpetB/adoptionList.jsp(60,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("infoList");
        // /JSP/IpetB/adoptionList.jsp(60,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infoSvc.getSupplyPet(123456)}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write(" \r\n");
              out.write("<!-- \t\t接session傳來的會員編號 -->\r\n");
              out.write("\t\t\t<tbody>\r\n");
              out.write("\t\t\t\t<!-- 標題區，點擊後會打開更多內容區 -->\r\n");
              out.write("\t\t\t\t<tr class=\"pet-title \">\r\n");
              out.write("\t\t\t\t\t<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infoList.petNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infoList.petName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infoList.petTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infoList.petDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infoList.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</td>\r\n");
              out.write("\t\t\t\t\t<td><button class=\"pet-edit pull-right btn btn-primary \">修改</button></td> \r\n");
              out.write("\t\t\t\t\t<td>\r\n");
              out.write("\t\t\t\t\t<FORM METHOD=\"post\"\tACTION=\"");
              out.print(request.getContextPath());
              out.write("/JSP/IpetB/addAdopt.do\">\r\n");
              out.write("\t\t\t\t\t\t<button class=\"pet-edit pull-right btn btn-primary\"> 修改</button>\r\n");
              out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"petNo\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infoList.petNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("\"> \r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<!--送出本網頁的路徑給Controller-->\r\n");
              out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"get_one_pet\">\r\n");
              out.write("\t\t\t\t\t</FORM>\r\n");
              out.write("\t\t\t\t</td>\r\n");
              out.write("\t\t\t\t<td>\r\n");
              out.write("\t\t\t\t\t<FORM METHOD=\"post\"\r\n");
              out.write("\t\t\t\t\t\tACTION=\"");
              out.print(request.getContextPath());
              out.write("/JSP/IpetB/addAdopt.do\">\r\n");
              out.write("\t\t\t\t\t\t<button class=\"pet-edit pull-right btn btn-primary\">刪除</button>\r\n");
              out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"empno\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empVO.empno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("\"> \r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t<!--送出本網頁的路徑給Controller-->\r\n");
              out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
              out.write("\t\t\t\t\t</FORM>\r\n");
              out.write("\t\t\t\t</td>\r\n");
              out.write("\t\t\t\t</tr>\r\n");
              out.write("\t\t\t</tbody>\r\n");
              out.write("\t\t");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        if (!_jspx_th_c_005fforEach_005f0_reused) {
          _jspx_th_c_005fforEach_005f0.release();
          _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f0);
        }
      }
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \t<tr class=\"pet-title\"> -->\r\n");
      out.write("<!-- \t\t<td>1234567</td> -->\r\n");
      out.write("<!-- \t\t<td>可愛小橘球找家人</td> -->\r\n");
      out.write("<!-- \t\t<td>2017/10/10</td> -->\r\n");
      out.write("<!-- \t\t<td>壞心人</td> -->\r\n");
      out.write("<!-- \t\t<td>已送養</td> -->\r\n");
      out.write("<!-- \t\t<td><button class=\"pet-edit pull-right btn btn-primary\">修改</button></td> -->\r\n");
      out.write("<!-- \t</tr> -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 標題區，點擊後會打開更多內容區 -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t<tr class=\"pet-adopt\"> -->\r\n");
      out.write("<!-- \t\t<td>11111111</td> -->\r\n");
      out.write("<!-- \t\t<td>我好想認養你</td> -->\r\n");
      out.write("<!-- \t\t<td>2017/10/10</td> -->\r\n");
      out.write("<!-- \t\t<td>金正恩</td> -->\r\n");
      out.write("<!-- \t\t<td>想領養</td> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t</tr> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 更多內容區 -->\r\n");
      out.write("\t<tr class=\"pet-content\">\r\n");
      out.write("\t\t<td colspan=\"5\">\r\n");
      out.write("\t\t\t<!-- 功能按鈕區 -->\r\n");
      out.write("\t\t\t<div class=\"btn-area col-sm-12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- \t\t\t\t\t\t<button class=\"pet-save pull-right btn btn-primary\">儲存</button> -->\r\n");
      out.write("\t\t\t\t<button class=\"pet-cancel  pull-right btn  btn-primary\">取消</button>\r\n");
      out.write("\t\t\t</div> <!-- 功能按鈕區 --> <!-- 可編輯的input 所有inpt請包在label標籤內-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"add-content\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6 pull-left\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i>填寫送養資料\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form class=\"col-xs-12 col-sm-12\" METHOD=\"post\"\r\n");
      out.write("\t\t\t\t\t\t\tenctype=\"multipart/form-data\"\r\n");
      out.write("\t\t\t\t\t\t\tACTION=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/addAdopt.do\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"add\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petName\">動物姓名</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"petName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"請填入動物的名字或暱稱\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.petName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolor=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petSex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t*<label class=\"radio-inline\">動物性別</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\"\tname=\"petSex\" value=\"公\" checked> 公 \r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\"\tname=\"petSex\" value=\"母\"> 母\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
      com.PetSpecies.model.PetSpeciesService speciesSvc = null;
      speciesSvc = (com.PetSpecies.model.PetSpeciesService) _jspx_page_context.getAttribute("speciesSvc", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (speciesSvc == null){
        speciesSvc = new com.PetSpecies.model.PetSpeciesService();
        _jspx_page_context.setAttribute("speciesSvc", speciesSvc, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group species\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"species\">動物類型</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"speciesNo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.speciesNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.speciesNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petColor\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petColor\">動物毛色</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"petColor\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"請填入動物的毛色\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.petColor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolor=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petColor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      com.PetBreed.model.PetBreedService breedSvc = null;
      breedSvc = (com.PetBreed.model.PetBreedService) _jspx_page_context.getAttribute("breedSvc", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (breedSvc == null){
        breedSvc = new com.PetBreed.model.PetBreedService();
        _jspx_page_context.setAttribute("breedSvc", breedSvc, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group breed\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petColor\">動物品種</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"petBreed\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.petBreed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petBreed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petAge\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label class=\"radio-inline\">年齡</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"petAge\" value=\"成年\" checked> 成年\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"petAge\" value=\"幼年\"> 幼年\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petSize\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petSize\">體型</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"petSize\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"大型\">大型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"中型\">中型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"小型\">小型</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petPosition\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petPosition\">送養縣市</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"position\" id=\"position\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">選擇縣市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"台北市\">台北市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"新北市\">新北市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"桃園市\">桃園市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"新竹市\">新竹市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"新竹縣\">新竹縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"宜蘭縣\">宜蘭縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"基隆市\">基隆市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"台中市\">台中市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"彰化縣\">彰化縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"雲林縣\">雲林縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"苗栗縣\">苗栗縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"南投縣\">南投縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"高雄市\">高雄市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"台南市\">台南市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"嘉義市\">嘉義市</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"嘉義縣\">嘉義縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"屏東縣\">屏東縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"台東縣\">台東縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"花蓮縣\">花蓮縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"澎湖縣\">澎湖縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"金門縣\">金門縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"連江縣\">連江縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.position}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"keyAddr\">送養地址</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"addr\" name=\"addr\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"請填入寵物所在地址\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolor=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petIc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\">晶片</label> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"petIc\" value=\"有\"> 有 <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"petIc\" value=\"無\" checked> 無\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group tnr\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"radio-inline\">絕育</label> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"TNR\" value=\"是\"> 是 <input type=\"radio\" name=\"TNR\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"否\" checked> 否\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petTitle\">送養標題</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"petTitle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.petTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" placeholder=\"請填入十個字內的送養標題\"> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolor=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petContent\">動物現況</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"form-control\" id=\"situation\" name=\"situation\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\trows=\"5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PetInformationVO.situation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.situation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"petTitle\">經度</label> <input type=\"text\" name=\"long\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"long\" >\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group petTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"petTitle\">緯度</label> <input type=\"text\" name=\"lat\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"lat\" >\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"petImage\"> 動物照片上傳 </label> <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control-file\" name=\"petImage1\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-describedby=\"fileHelp\"> <small name=\"igname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-text text-muted\"></small> <span class=\"text-danger\">*</span><label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor=\"image\">照片名稱</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"picName1\" name=\"picName1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"請填入照片名稱\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.picName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> <font\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolor=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.picName1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"petFilm\"> 動物影片上傳 <span>（限一部）</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label> <input type=\"file\" class=\"form-control-file\" name=\"petFilm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-describedby=\"fileHelp\"> <small id=\"petFilm\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-text text-muted\"></small>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"update\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"pet-save btn btn-primary pull-right\">確認送出</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<!-- 更多內容區 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/js/adopt.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /JSP/IpetB/adoptionList.jsp(157,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("speciesVO");
      // /JSP/IpetB/adoptionList.jsp(157,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${speciesSvc.all}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${speciesVO.speciesNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(PetSpeciesVO.speciesNo==speciesVO.speciesNo)? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${speciesVO.speciesName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f1_reused) {
        _jspx_th_c_005fforEach_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /JSP/IpetB/adoptionList.jsp(178,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("breedVO");
      // /JSP/IpetB/adoptionList.jsp(178,9) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${breedSvc.all}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${breedVO.breedNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(PetBreedVO.breedNo==breedVO.breedNo)? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${breedVO.breedName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f2_reused) {
        _jspx_th_c_005fforEach_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f2);
      }
    }
    return false;
  }
}
