/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-09-24 10:08:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP.IpetB;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.PetSpecies.model.*;
import com.petInformation.model.*;
import com.PetBreed.model.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	PetSpeciesService speciesSvc = new PetSpeciesService();
	List<PetSpeciesVO> species = speciesSvc.getAll();
	pageContext.setAttribute("species", species);

	PetInformationService petInfoSvc = new PetInformationService();
	List<PetInformationVO> list = petInfoSvc.getAll();
	pageContext.setAttribute("list", list);

	PetBreedService breedSvc = new PetBreedService();
	List<PetBreedVO> breedVO = breedSvc.getAll();
	pageContext.setAttribute("breedVO", breedVO);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>iPet愛動物</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--第一區：nav區-->\r\n");
      out.write("\t<div class=\"b_nav\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--左欄：logo區-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-2 col-sm-2\">\r\n");
      out.write("\t\t\t\t<a class=\"logo\" href=\"index.html\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/Ipet_Logo .png\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--左欄：logo區 end-->\r\n");
      out.write("\t\t\t<!--手機版的漢堡選單開始-->\r\n");
      out.write("\t\t\t<div class=\"burger-menu\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--手機版的漢堡選單結束-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--右欄：購物車等icon＋選單區-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-10 col-sm-10 rightbar text-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--購物車、註冊、登入、會員專區（登入成功後，登入兩字變為會員專區）-->\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon shopping\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"fa fa-cart-plus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i>購物車</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon member\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"fa fa-user-o\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i>加入會員</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon login\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"fa fa-user-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i>登入</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--購物車、註冊、登入、會員專區（登入成功後，登入兩字變為會員專區）end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--選單區-->\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"adopt.html\">我要認養</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">自我評估</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"adopt.html\">認養總覽</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"addadoption.html\">我要送養</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">送養須知</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"addadoption.html\">新增送養</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"shopping.html\">購物商城</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">討論區</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">寵物牆</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">活動專區</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">本版活動</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">領養分享</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--選單區 end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--右欄：購物車等icon＋選單區 end-->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--第一區：nav區 end-->\r\n");
      out.write("\r\n");
      out.write("\t<!--第二區：Banner區 領養心得-->\r\n");
      out.write("\t<div id=\"carousel-id\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t<!-- 幻燈片小圓點區 -->\r\n");
      out.write("\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#carousel-id\" data-slide-to=\"0\" class=\"\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#carousel-id\" data-slide-to=\"1\" class=\"\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#carousel-id\" data-slide-to=\"2\" class=\"active\"></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t\t<!-- 幻燈片主圖區 -->\r\n");
      out.write("\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img src=\"images/dog21_18X9_副本.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h1>以領養替代購買</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>希望您可以此找到珍愛一輩子的寵物</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">詳細內容</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t<img src=\"images/dog55_副本.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h1>以領養替代購買</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>希望您可以在此找到珍愛一輩子的寵物</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-primary\" href=\"#\">詳細內容</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t<img src=\"images/dog22_18X9.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t<h1>以領養替代購買</h1>\r\n");
      out.write("\t\t\t\t\t\t<p>希望您可以在此找到珍愛一輩子的寵物</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn btn-primary\" href=\"#\" role=\"button\">詳細內容</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 上下頁控制區 -->\r\n");
      out.write("\t<a class=\"left carousel-control\" href=\"#carousel-id\" data-slide=\"prev\"><span\r\n");
      out.write("\t\tclass=\"glyphicon glyphicon-chevron-left\"></span></a>\r\n");
      out.write("\t<a class=\"right carousel-control\" href=\"#carousel-id\" data-slide=\"next\"><span\r\n");
      out.write("\t\tclass=\"glyphicon glyphicon-chevron-right\"></span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--第二區：Banner區 end-->\r\n");
      out.write("\r\n");
      out.write("\t<!--第三區： 領養posts-->\r\n");
      out.write("\t<div class=\"post-content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--各區的主標題-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 title-area\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab col-sm-3 tab-active\">推薦領養</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab col-sm-3\">最新送養</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title right text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-info\">看更多</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-info\">我要領養</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--各區的主標題 end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--各區的主內容-->\r\n");
      out.write("\t\t\t<!--第1則-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/31.jpg\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第1則end-->\r\n");
      out.write("\t\t\t<!--第2則-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/31.jpg\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">可愛活潑～小橘球</a>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>認養前請再三考慮，不要衝動承諾認養後需耐心對待，不要輕言放棄……</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第2則end-->\r\n");
      out.write("\t\t\t<!--第3則-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/31.jpg\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">可愛活潑～小橘球</a>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>認養前請再三考慮，不要衝動承諾認養後需耐心對待，不要輕言放棄……</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第3則end-->\r\n");
      out.write("\t\t\t<!--第4則-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/31.jpg\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">可愛活潑～小橘球</a>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>認養前請再三考慮，不要衝動承諾認養後需耐心對待，不要輕言放棄……</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第4則end-->\r\n");
      out.write("\t\t\t<!--第5則-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/PetImage.do?picNo=4\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/PetImage.do?picNo=12\">可愛活潑～小橘球</a>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>認養前請再三考慮，不要衝動承諾認養後需耐心對待，不要輕言放棄……</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第5則end-->\r\n");
      out.write("\t\t\t<!--第6則-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/31.jpg\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">可愛活潑～小橘球</a>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>認養前請再三考慮，不要衝動承諾認養後需耐心對待，不要輕言放棄……</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第6則end-->\r\n");
      out.write("\t\t\t<!--第7則-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/31.jpg\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">可愛活潑～小橘球</a>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>認養前請再三考慮，不要衝動承諾認養後需耐心對待，不要輕言放棄……</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第7則end-->\r\n");
      out.write("\t\t\t<!--第8則-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-6 col-sm-3\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/31.jpg\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"post-text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\">可愛活潑～小橘球</a>\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>認養前請再三考慮，不要衝動承諾認養後需耐心對待，不要輕言放棄……</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第8則end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--第四區： 討論區-->\r\n");
      out.write("\t<div class=\"discuss-content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!--各區的主標題-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 title-area\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab col-sm-3 tab-active\">熱門討論</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--<div class=\"tab col-sm-3\">最新送養</div>-->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title right text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-info\">看更多</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-info\">我要發表</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--各區的主標題 end-->\r\n");
      out.write("\t\t\t<!--各區的主內容-->\r\n");
      out.write("\t\t\t<!--第1則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<div class=\"discussion\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/14.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>主題：</span>求推薦～帶狗狗奔跑的好地方\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>想帶狗狗去跑跑，台北地區有推薦的好地方嗎？</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第1則end-->\r\n");
      out.write("\t\t\t<!--第2則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<div class=\"discussion\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/14.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>主題：</span>求推薦～帶狗狗奔跑的好地方\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>想帶狗狗去跑跑，台北地區有推薦的好地方嗎？</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第2則end-->\r\n");
      out.write("\t\t\t<!--第3則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<div class=\"discussion\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/14.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>主題：</span>求推薦～帶狗狗奔跑的好地方\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>想帶狗狗去跑跑，台北地區有推薦的好地方嗎？</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第3則end-->\r\n");
      out.write("\t\t\t<!--第4則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<div class=\"discussion\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/14.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t<span>主題：</span>求推薦～帶狗狗奔跑的好地方\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>想帶狗狗去跑跑，台北地區有推薦的好地方嗎？</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第4則end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--各區的主內容 end-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--第四區：討論區end-->\r\n");
      out.write("\r\n");
      out.write("\t<!--第五區：商品區-->\r\n");
      out.write("\t<div class=\"products-content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!--各區的主標題-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 title-area\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab col-sm-3 tab-active\">熱門商品</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab col-sm-3\">最新商品</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title right text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-info\">看更多</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--各區的主標題 end-->\r\n");
      out.write("\t\t\t<!--各區主內容-->\r\n");
      out.write("\t\t\t<!--第1則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/cat1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>貓貓最愛糧食</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>$3000元</p>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-cart-plus\" aria-hidden=\"true\"></i>加入購物車\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第1則end-->\r\n");
      out.write("\t\t\t<!--第2則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/cat1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>貓貓最愛糧食</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>$3000元</p>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-cart-plus\" aria-hidden=\"true\"></i>加入購物車\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第2則end-->\r\n");
      out.write("\t\t\t<!--第3則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/cat1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>貓貓最愛糧食</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>$3000元</p>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-cart-plus\" aria-hidden=\"true\"></i>加入購物車\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第3則end-->\r\n");
      out.write("\t\t\t<!--第4則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/cat1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>貓貓最愛糧食</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>$3000元</p>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-cart-plus\" aria-hidden=\"true\"></i>加入購物車\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第4則end-->\r\n");
      out.write("\t\t\t<!--第5則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/cat1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>貓貓最愛糧食</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>$3000元</p>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-cart-plus\" aria-hidden=\"true\"></i>加入購物車\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第5則end-->\r\n");
      out.write("\t\t\t<!--第6則-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t<div class=\"product\">\r\n");
      out.write("\t\t\t\t\t<div class=\"img\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/cat1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t<h3>貓貓最愛糧食</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>$3000元</p>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-cart-plus\" aria-hidden=\"true\"></i>加入購物車\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--第6則end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--各區主內容 ㄎ-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--第五區：商品區 end-->\r\n");
      out.write("\r\n");
      out.write("\t<!--第六區：寵物協尋-->\r\n");
      out.write("\t<div class=\"finding-content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<!--各區的主標題-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-12 title-area\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title left\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tab col-sm-3 tab-active\">寵物協尋</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--<div class=\"tab col-sm-3\">最新送養</div>-->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"title right text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-info\">看更多</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-info\">我要協尋</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--各區的主標題 end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--各區的主內容-->\r\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"finding-post\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>急！！！狗狗在河濱公園遺失，幫忙找找！</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"finding-post\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>狗狗在河濱公園遺失，幫忙找找！</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"finding-post\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>狗狗在河濱公園遺失，幫忙找找！</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"finding-post\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>狗狗在河濱公園遺失，幫忙找找！</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"finding-post\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/16.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>狗狗在河濱公園遺失，幫忙找找！</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"finding-post\">\r\n");
      out.write("\t\t\t\t\t\t\t<img class=\"img-responsive\" src=\"images/11.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>狗狗在河濱公園遺失，幫忙找找！</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--各區的主內容 end-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--第六區：寵物協尋 end-->\r\n");
      out.write("\r\n");
      out.write("\t<!--最後一區：footer-->\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"container\"></div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!--最後一區：end-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /JSP/IpetB/Index.jsp(204,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("titleVO");
      // /JSP/IpetB/Index.jsp(204,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<div class=\"post-text\">\r\n");
            out.write("\t\t\t\t\t\t\t<h3>\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"#\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${titleVO.petTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a>\r\n");
            out.write("\t\t\t\t\t\t\t</h3>\r\n");
            out.write("\t\t\t\t\t\t\t<p>認養前請再三考慮，不要衝動承諾認養後需耐心對待，不要輕言放棄……</p>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f0_reused) {
        _jspx_th_c_005fforEach_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f0);
      }
    }
    return false;
  }
}
