/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-09-28 13:23:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP.IpetB;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.PetBreed.model.*;
import com.PetSpecies.model.*;
import com.petInformation.model.*;
import com.PetImage.model.*;
import java.util.*;
import com.PetView.model.*;

public final class updateAdopt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

// 	PetInformationVO petInfoVO = (PetInformationVO) request.getAttribute("PetInformationVO"); //記憶動物table寫錯資料時，其他正確的內容
// 	PetBreedVO breedVOe = (PetBreedVO) request.getAttribute("PetBreedVO"); //記憶使用者輸入品種的選項，
// 	PetSpeciesVO speciesVO = (PetSpeciesVO) request.getAttribute("PetSpeciesVO"); //記憶使用者輸入種類的選項
// 	PetImageVO imageVO = (PetImageVO) request.getAttribute("PetImageVO"); //記憶使用者輸入的照片和標題

PetViewVO petViewVO = (PetViewVO) request.getAttribute("PetViewVO");
System.out.println(petViewVO.getPetPosition().substring(0,3));

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"js/main.js\"></script> -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCVTvj_0kUlIT4NDFTo4AV0ZJbliitGrPQ\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/js/Address.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/css/nav.css\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/js/main.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/js/Address.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>iPet愛動物</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--第一區：nav區-->\r\n");
      out.write("\t<div class=\"b_nav\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--左欄：logo區-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-2 col-sm-2\">\r\n");
      out.write("\t\t\t\t<a class=\"logo\" href=\"index.html\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"images/Ipet_Logo .png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--左欄：logo區 end-->\r\n");
      out.write("\t\t\t<!--手機版的漢堡選單開始-->\r\n");
      out.write("\t\t\t<div class=\"burger-menu\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-bars\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--手機版的漢堡選單結束-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--右欄：購物車等icon＋選單區-->\r\n");
      out.write("\t\t\t<div class=\"col-xs-10 col-sm-10 rightbar text-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--購物車、註冊、登入、會員專區（登入成功後，登入兩字變為會員專區）-->\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon shopping\">\r\n");
      out.write("\t\t\t\t\t\t\t<span> <a href=\"#\"> <i class=\"fa fa-cart-plus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> 購物車\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon member\">\r\n");
      out.write("\t\t\t\t\t\t\t<span> <a href=\"#\"> <i class=\"fa fa-user-o\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> 加入會員\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"icon login\">\r\n");
      out.write("\t\t\t\t\t\t\t<span> <a href=\"#\"> <i class=\"fa fa-user-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-hidden=\"true\"></i> 登入\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--購物車、註冊、登入、會員專區（登入成功後，登入兩字變為會員專區）end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--選單區-->\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"adopt.html\">我要認養</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">自我評估</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"adopt.html\">認養總覽</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"addadoption.html\">我要送養</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">送養須知</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"addadoption.html\">新增送養</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"shopping.html\">購物商城</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">討論區</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">寵物牆</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">活動專區</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">本版活動</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"#\">領養分享</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--選單區 end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--右欄：購物車等icon＋選單區 end-->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--第一區：nav區 end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--各頁主內容寫在這-->\r\n");
      out.write("\t<div class=\"add-content\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 add-img\">\r\n");
      out.write("\t\t\t\t<img src=\"images/cat.png\" alt=\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6 pull-right\">\r\n");
      out.write("\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-pencil-square-o\" aria-hidden=\"true\"></i>修改送養資料\r\n");
      out.write("\t\t\t\t</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form class=\"col-xs-12 col-sm-12\" METHOD=\"post\"\r\n");
      out.write("\t\t\t\t\tenctype=\"multipart/form-data\"\r\n");
      out.write("\t\t\t\t\tACTION=\"");
      out.print(request.getContextPath());
      out.write("/JSP/IpetB/addAdopt.do\"\r\n");
      out.write("\t\t\t\t\tname=\"add\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petName\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petName\">動物姓名</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"petName\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"請填入動物的名字或暱稱\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PetViewVO.petName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> \r\n");
      out.write("\t\t\t\t\t\t\t<font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petSex\">\r\n");
      out.write("\t\t\t\t\t\t*<label class=\"radio-inline\">動物性別</label> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\"\tname=\"petSex\" value=\"公\" ");
      out.print((petViewVO.getPetSex().equals("公"))? "checked" : "" );
      out.write("> 公 \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\"\tname=\"petSex\" value=\"母\" ");
      out.print((petViewVO.getPetSex().equals("母"))? "checked" : "" );
      out.write("> 母\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      com.PetSpecies.model.PetSpeciesService speciesSvc = null;
      speciesSvc = (com.PetSpecies.model.PetSpeciesService) _jspx_page_context.getAttribute("speciesSvc", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (speciesSvc == null){
        speciesSvc = new com.PetSpecies.model.PetSpeciesService();
        _jspx_page_context.setAttribute("speciesSvc", speciesSvc, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group species\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"species\">動物類型</label>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" name=\"speciesNo\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.speciesNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petColor\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petColor\">動物毛色</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"petColor\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"請填入動物的毛色\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PetViewVO.petColor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /> <font\r\n");
      out.write("\t\t\t\t\t\t\tcolor=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petColor}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      com.PetBreed.model.PetBreedService breedSvc = null;
      breedSvc = (com.PetBreed.model.PetBreedService) _jspx_page_context.getAttribute("breedSvc", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (breedSvc == null){
        breedSvc = new com.PetBreed.model.PetBreedService();
        _jspx_page_context.setAttribute("breedSvc", breedSvc, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group breed\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petColor\">動物品種</label>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" name=\"petBreed\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.petBreed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petBreed}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petAge\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label class=\"radio-inline\">年齡</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"petAge\" value=\"成年\" ");
      out.print((petViewVO.getPetAge().equals("成年"))? "checked" : "" );
      out.write("> 成年 \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"petAge\" value=\"幼年\" ");
      out.print((petViewVO.getPetAge().equals("幼年"))? "checked" : "" );
      out.write("> 幼年\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petSize\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petSize\">體型</label>\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" name=\"petSize\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PetViewVO.petSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">請選擇</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"大型\" ");
      out.print(petViewVO.getPetSize().equals("大型") ? "select" :"" );
      out.write(">大型</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"中型\" ");
      out.print(petViewVO.getPetSize().equals("中型") ? "select" :"" );
      out.write(">中型</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"小型\" ");
      out.print(petViewVO.getPetSize().equals("小型") ? "select" :"" );
      out.write(">小型</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("<!-- 因為資料庫沒有縣市這個欄位，只能用subString(起始位置,結束位置)去切 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petPosition\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petPosition\">送養縣市</label>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"position\" id=\"position\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">選擇縣市</option>     \r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"台北市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("台北市") ? "select" :"" );
      out.write(">台北市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"新北市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("新北市") ? "select" :"" );
      out.write(">新北市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"桃園市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("桃園市") ? "select" :"" );
      out.write(">桃園市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"新竹市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("新竹市") ? "select" :"" );
      out.write(">新竹市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"新竹縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("新竹縣") ? "select" :"" );
      out.write(">新竹縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"宜蘭縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("宜蘭縣") ? "select" :"" );
      out.write(">宜蘭縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"基隆市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("基隆市") ? "select" :"" );
      out.write(">基隆市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"台中市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("台中市") ? "select" :"" );
      out.write(">台中市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"彰化縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("彰化市") ? "select" :"" );
      out.write(">彰化縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"雲林縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("雲林縣") ? "select" :"" );
      out.write(">雲林縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"苗栗縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("苗集縣") ? "select" :"" );
      out.write(">苗栗縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"南投縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("南投縣") ? "select" :"" );
      out.write(">南投縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"高雄市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("高雄市") ? "select" :"" );
      out.write(">高雄市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"台南市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("台南市") ? "select" :"" );
      out.write(">台南市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"嘉義市\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("嘉義市") ? "select" :"" );
      out.write(">嘉義市</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"嘉義縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("嘉義縣") ? "select" :"" );
      out.write(">嘉義縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"屏東縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("屏東縣") ? "select" :"" );
      out.write(">屏東縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"台東縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("台東縣") ? "select" :"" );
      out.write(">台東縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"花蓮縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("花蓮縣") ? "select" :"" );
      out.write(">花蓮縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"澎湖縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("澎湖縣") ? "select" :"" );
      out.write(">澎湖縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"金門縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("金門縣") ? "select" :"" );
      out.write(">金門縣</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"連江縣\" ");
      out.print(petViewVO.getPetPosition().substring(0,3).equals("連江縣") ? "select" :"" );
      out.write(">連江縣</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.position}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"keyAddr\">送養地址</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"addr\" name=\"addr\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"請填入寵物所在地址\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PetViewVO.getPetPosition().substring(3)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> <font\r\n");
      out.write("\t\t\t\t\t\t\tcolor=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petIc\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"radio-inline\">晶片</label> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\"\tname=\"petIc\" value=\"有\" ");
      out.print((petViewVO.getPetIc().equals("有"))? "checked" : "" );
      out.write("> 有\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\"\tname=\"petIc\" value=\"無\" ");
      out.print((petViewVO.getPetIc().equals("無"))? "checked" : "" );
      out.write("> 無\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group tnr\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"radio-inline\">絕育</label> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\"\tname=\"TNR\" value=\"是\" ");
      out.print((petViewVO.getTNR().equals("是"))? "checked" : "" );
      out.write("> 是 \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"TNR\" value=\"否\" ");
      out.print((petViewVO.getTNR().equals("否"))? "checked" : "" );
      out.write("> 否\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petTitle\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petTitle\">送養標題</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"petTitle\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PetViewVO.petTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" placeholder=\"請填入十個字內的送養標題\"> <font\r\n");
      out.write("\t\t\t\t\t\t\tcolor=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.petTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petContent\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"text-danger\">*</span><label for=\"petContent\">動物現況</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" id=\"situation\" name=\"situation\"\r\n");
      out.write("\t\t\t\t\t\t\trows=\"5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PetViewVO.situation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.situation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petTitle\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"petTitle\">經度</label> <input type=\"text\" name=\"long\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"long\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group petTitle\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"petTitle\">緯度</label> <input type=\"text\" name=\"lat\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"lat\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"petImage\"> 動物照片上傳 </label> <input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control-file\" name=\"petImage1\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\taria-describedby=\"fileHelp\"> <small name=\"igname\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-text text-muted\"></small> <span class=\"text-danger\">*</span><label\r\n");
      out.write("\t\t\t\t\t\t\tfor=\"image\">照片名稱</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"picName1\" name=\"picName1\" placeholder=\"請填入照片名稱\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.picName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsgs.picName1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"petFilm\"> 動物影片上傳 <span>（限一部）</span>\r\n");
      out.write("\t\t\t\t\t\t</label> <input type=\"file\" class=\"form-control-file\" name=\"petFilm\"\r\n");
      out.write("\t\t\t\t\t\t\taria-describedby=\"fileHelp\"> <small id=\"petFilm\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-text text-muted\"></small>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"update\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary pull-right\">確認送出</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--各頁主內容寫在這 end-->\r\n");
      out.write("\r\n");
      out.write("\t<!--最後一區：footer-->\r\n");
      out.write("\t<!-- <footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </footer> -->\r\n");
      out.write("\r\n");
      out.write("\t<!--最後一區：end-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /JSP/IpetB/updateAdopt.jsp(172,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("speciesVO");
      // /JSP/IpetB/updateAdopt.jsp(172,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${speciesSvc.all}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${speciesVO.speciesNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(speciesVO.speciesNo == PetViewVO.speciesNo)? 'selected': \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${speciesVO.speciesName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f0_reused) {
        _jspx_th_c_005fforEach_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /JSP/IpetB/updateAdopt.jsp(193,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("breedVO");
      // /JSP/IpetB/updateAdopt.jsp(193,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${breedSvc.all}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${breedVO.breedNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(breedVO.breedNo==PetViewVO.breedNo)? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${breedVO.breedName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f1_reused) {
        _jspx_th_c_005fforEach_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f1);
      }
    }
    return false;
  }
}
